# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "patient" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"archived" BOOLEAN NOT NULL,"firstName" VARCHAR NOT NULL,"lastName" VARCHAR NOT NULL,"gender" VARCHAR NOT NULL,"dateOfBirth" DATE NOT NULL,"phone" VARCHAR,"email" VARCHAR,"address1" VARCHAR,"postcode" VARCHAR);

# --- !Downs

drop table "patient";

